# Lab 11: Dialogue Act Tagging

Dialogue act (DA) tagging is an important step in the process of developing dialog systems. DA tagging is a problem usually solved by supervised machine learning approaches that all require large amounts of hand labeled data. A wide range of techniques have been investigated for DA tagging. In this lab, we explore two approaches to DA classification. We are using the Switchboard Dialog Act Corpus for training.
Corpus can be downloaded from http://compprag.christopherpotts.net/swda.html.


The downloaded dataset should be kept in a data folder in the same directory as this file. 

In [0]:
import pandas as pd
import glob
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import numpy as np
import sklearn.metrics
import tensorflow as tf
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook as tqdm

In [8]:
from google.colab import drive
drive.mount('/content/drive')
!ls ("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/bin/bash: -c: line 0: syntax error near unexpected token `"/content/drive"'
/bin/bash: -c: line 0: `ls ("/content/drive")'


In [0]:
f = glob.glob("/content/drive/My Drive/swda/sw*/sw*.csv")
frames = []
for i in range(0, len(f)):
    frames.append(pd.read_csv(f[i]))

result = pd.concat(frames, ignore_index=True)

In [10]:
print("Number of converations in the dataset:",len(result))

Number of converations in the dataset: 223606


The dataset has many different features, we are only using act_tag and text for this training.


In [0]:
reduced_df = result[['act_tag','text']]

Reduce down the number of tags to 43 - converting the combined tags to their generic classes:

In [0]:
# Imported from "https://github.com/cgpotts/swda"
# Convert the combination tags to the generic 43 tags

import re
def damsl_act_tag(input):
        """
        Seeks to duplicate the tag simplification described at the
        Coders' Manual: http://www.stanford.edu/~jurafsky/ws97/manual.august1.html
        """
        d_tags = []
        tags = re.split(r"\s*[,;]\s*", input)
        for tag in tags:
            if tag in ('qy^d', 'qw^d', 'b^m'): pass
            elif tag == 'nn^e': tag = 'ng'
            elif tag == 'ny^e': tag = 'na'
            else: 
                tag = re.sub(r'(.)\^.*', r'\1', tag)
                tag = re.sub(r'[\(\)@*]', '', tag)            
                if tag in ('qr', 'qy'):                         tag = 'qy'
                elif tag in ('fe', 'ba'):                       tag = 'ba'
                elif tag in ('oo', 'co', 'cc'):                 tag = 'oo_co_cc'
                elif tag in ('fx', 'sv'):                       tag = 'sv'
                elif tag in ('aap', 'am'):                      tag = 'aap_am'
                elif tag in ('arp', 'nd'):                      tag = 'arp_nd'
                elif tag in ('fo', 'o', 'fw', '"', 'by', 'bc'): tag = 'fo_o_fw_"_by_bc'            
            d_tags.append(tag)
        # Dan J says (p.c.) that it makes sense to take the first;
        # there are only a handful of examples with 2 tags here.
        return d_tags[0]

In [13]:
reduced_df["act_tag"] = reduced_df["act_tag"].apply(lambda x: damsl_act_tag(x))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


There are 43 tags in this dataset. Some of the tags are Yes-No-Question('qy'), Statement-non-opinion('sd') and Statement-opinion('sv'). Tags information can be found here http://compprag.christopherpotts.net/swda.html#tags. 


To get unique tags:

In [69]:
unique_tags = set()
for tag in reduced_df['act_tag']:
    unique_tags.add(tag)

count = 1
for tag in unique_tags:
  print(str(count) + "-" + tag)
  count += 1

1-aa
2-sd
3-ar
4-qo
5-^q
6-x
7-fo_o_fw_"_by_bc
8-qw^d
9-qh
10-b^m
11-ad
12-ba
13-t1
14-oo_co_cc
15-b
16-nn
17-na
18-h
19-sv
20-ft
21-bf
22-%
23-+
24-bd
25-^h
26-ny
27-fp
28-qy^d
29-fa
30-aap_am
31-bk
32-no
33-t3
34-br
35-bh
36-qw
37-^g
38-^2
39-ng
40-qy
41-arp_nd
42-fc
43-qrr


In [0]:
one_hot_encoding_dic = pd.get_dummies(list(unique_tags))

In [0]:
tags_encoding = []
for i in range(0, len(reduced_df)):
    tags_encoding.append(one_hot_encoding_dic[reduced_df['act_tag'].iloc[i]])

The tags are one hot encoded.

To create sentence embeddings:

In [0]:
sentences = []
for i in range(0, len(reduced_df)):
    sentences.append(reduced_df['text'].iloc[i].split(" "))

In [0]:
wordvectors = {}
index = 1
for s in sentences:
    for w in s:
        if w not in wordvectors:
            wordvectors[w] = index
            index += 1

In [0]:
# Max length of 137
MAX_LENGTH = len(max(sentences, key=len))

In [0]:
sentence_embeddings = []
for s in sentences:
    sentence_emb = []
    for w in s:
        sentence_emb.append(wordvectors[w])
    sentence_embeddings.append(sentence_emb)

Then we split the dataset into test and train.

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(sentence_embeddings, np.array(tags_encoding))

And pad the sentences with zero to make all sentences of equal length.


In [0]:
MAX_LENGTH = 137

In [0]:
from keras.preprocessing.sequence import pad_sequences
 
train_sentences_X = pad_sequences(X_train, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(X_test, maxlen=MAX_LENGTH, padding='post')

In [0]:
train_input = train_sentences_X[:140000]
val_input = train_sentences_X[140000:]

train_labels = y_train[:140000]
val_labels = y_train[140000:]

# Model 1 - 

The first approach we'll try is to treat DA tagging as a standard multi-class text classification task, in the way you've done before with sentiment analysis and other tasks. Each utterance will be treated independently as a text to be classified with its DA tag label. This model has an architecture of:

- Embedding  
- BLSTM  
- Fully Connected Layer
- Softmax Activation

 The model architecture is as follows: Embedding Layer (to generate word embeddings) Next layer Bidirectional LSTM. Feed forward layer with number of neurons = number of tags. Softmax activation to get the probabilities.


In [0]:
VOCAB_SIZE = len(wordvectors) # 43,731
MAX_LENGTH = len(max(sentences, key=len))
EMBED_SIZE = 100 # arbitary
HIDDEN_SIZE = len(unique_tags) 

In [26]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Dropout, InputLayer, Bidirectional, TimeDistributed, Activation, Embedding
from keras.optimizers import Adam

#Building the network
model = Sequential()
# Include 2 BLSTM layers, in order to capture both the forward and backward hidden states
# Embedding layer
model.add(Embedding(VOCAB_SIZE, EMBED_SIZE, input_length = MAX_LENGTH))
# Bidirectional 1
model.add(Bidirectional(LSTM(HIDDEN_SIZE, return_sequences=True)))
# Bidirectional 2
model.add(Bidirectional(LSTM(HIDDEN_SIZE)))
# Dense layer
model.add(Dense(HIDDEN_SIZE))
# Activation
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 137, 100)          4373100   
_________________________________________________________________
bidirectional_1 (Bidirection (None, 137, 86)           49536     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 86)                44720     
_________________________________________________________________
dense_1 (Dense)              (None, 43)                3741      
_________________________________________________________________
activation_1 (Activation)    (None, 43)                0         
Total params: 4,471,097
Trainable params: 4,471,097
Non-trainable params: 0
_________________________________________________________________


In [27]:
# Train the model - using validation 
model.fit(train_input, train_labels, batch_size=512, epochs=3, validation_data=(val_input, val_labels))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 140000 samples, validate on 27704 samples
Epoch 1/3
140000/140000 [==============================] - 358s 3ms/step - loss: 1.7517 - accuracy: 0.5291 - val_loss: 1.3637 - val_accuracy: 0.6187
Epoch 2/3
140000/140000 [==============================] - 350s 3ms/step - loss: 1.2108 - accuracy: 0.6516 - val_loss: 1.1408 - val_accuracy: 0.6674
Epoch 3/3
140000/140000 [==============================] - 349s 2ms/step - loss: 1.0309 - accuracy: 0.7032 - val_loss: 1.0749 - val_accuracy: 0.6833


In [46]:
score = model.evaluate(test_sentences_X, y_test, batch_size=100)

55902/55902 [==============================] - 3s 52us/step


In [47]:
print("Overall Accuracy:", score[1]*100)

Overall Accuracy: 70.46080827713013


## Evaluation


The overall accuracy is 67%, an effective accuracy for this task.

In addition to overall accuracy, you need to look at the accuracy of some minority classes. Signal-non-understanding ('br') is a good indicator of "other-repair" or cases in which the other conversational participant attempts to repair the speaker's error. Summarize/reformulate ('bf') has been used in dialogue summarization. Report the accuracy for these classes and some frequent errors you notice the system makes in predicting them. What do you think the reasons are？

## Minority Classes

In [48]:
# Generate predictions for the test data
generate_test_pred = model.predict(test_sentences_X, batch_size=100)
print(generate_test_pred)

[[2.2740885e-04 6.0133183e-01 6.3432424e-05 ... 6.0046732e-04
  6.4304858e-02 2.8837247e-05]
 [1.5235813e-01 1.3452207e-04 3.0221130e-05 ... 1.2298423e-04
  1.0983916e-03 3.4793328e-07]
 [4.1430299e-05 9.3947524e-01 4.3663595e-06 ... 6.7220964e-05
  1.1845243e-04 1.1921462e-05]
 ...
 [1.3241613e-02 5.5170993e-05 5.0603976e-06 ... 4.6123387e-05
  2.5910011e-03 1.7073411e-06]
 [3.0896487e-03 2.5652664e-05 8.5570878e-07 ... 6.4598726e-06
  9.6556137e-04 1.0871341e-06]
 [5.1337037e-02 3.8717888e-05 1.0910450e-05 ... 8.9077090e-05
  1.7908460e-03 1.9788281e-06]]


In [59]:
# Build the confusion matrix off these predictions
matrix_balanced = sklearn.metrics.confusion_matrix(y_test.argmax(axis=1), generate_test_pred.argmax(axis=1))
print(matrix_balanced)

matrix_balanced = matrix_balanced.astype('float')/matrix_balanced.sum(axis=1)[:,np.newaxis]
matrix_balanced= matrix_balanced.diagonal()

[[  782   135     0 ...     0     9     0]
 [  115 16066     1 ...     0    34     7]
 [    2    16     0 ...     0     0     0]
 ...
 [    0    30     0 ...     0     0     0]
 [   12    80     0 ...     0   386     2]
 [    0     5     0 ...     0     0    34]]


In [71]:
# Calculate Accuracies for "br" and "bf"
# sklearn.metrics.accuracy_score(y_test.argmax(axis = 1), generate_test_pred.argmax(axis = 1), normalize=True, sample_weight=None)
bf_accuracy = matrix_balanced[20]
br_accuracy = matrix_balanced[33]

print(bf_accuracy)
print(br_accuracy)

0.05627705627705628
0.5342465753424658



Due to the reduced lack of training data for the minority classes, these minority classifiers will not be very confident in classification, as they have not been fully optimised. The frequent classifiers will be more optimised and will generate more confident scores for all examples, effectively crowding out the less confident minority classifiers. 




# Model 2 - Balanced Network


One thing we can do to try to improve performance is therefore to balance the data more sensibly. As the dataset is highly imbalanced, we can simply weight up the minority classes proportionally to their underrepresentation while training. 

In [0]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

y_integers = np.argmax(tags_encoding, axis=1)
class_weights = compute_class_weight('balanced', np.unique(y_integers), y_integers)
d_class_weights = dict(enumerate(class_weights))

## Define & Train the model

In [34]:
# Re-built the model for the balanced training
#Building the network
balanced_model = Sequential()
# Include 2 BLSTM layers, in order to capture both the forward and backward hidden states
# Embedding layer
balanced_model.add(Embedding(VOCAB_SIZE, EMBED_SIZE, input_length = MAX_LENGTH))
# Bidirectional 1
balanced_model.add(Bidirectional(LSTM(HIDDEN_SIZE, return_sequences=True)))
# Bidirectional 2
balanced_model.add(Bidirectional(LSTM(HIDDEN_SIZE)))
# Dense layer
balanced_model.add(Dense(HIDDEN_SIZE))
# Activation
balanced_model.add(Activation('softmax'))
balanced_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

balanced_model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 137, 100)          4373100   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 137, 86)           49536     
_________________________________________________________________
bidirectional_4 (Bidirection (None, 86)                44720     
_________________________________________________________________
dense_2 (Dense)              (None, 43)                3741      
_________________________________________________________________
activation_2 (Activation)    (None, 43)                0         
Total params: 4,471,097
Trainable params: 4,471,097
Non-trainable params: 0
_________________________________________________________________


In [35]:
# Train the balanced network -  takes  time to achieve good accuracy
balanced_model.fit(train_input, train_labels, batch_size=512, epochs=3, validation_data=(val_input, val_labels))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 140000 samples, validate on 27704 samples
Epoch 1/3
140000/140000 [==============================] - 356s 3ms/step - loss: 1.7512 - accuracy: 0.5272 - val_loss: 1.3435 - val_accuracy: 0.6221
Epoch 2/3
140000/140000 [==============================] - 355s 3ms/step - loss: 1.2204 - accuracy: 0.6528 - val_loss: 1.1610 - val_accuracy: 0.6604
Epoch 3/3
140000/140000 [==============================] - 356s 3ms/step - loss: 1.0207 - accuracy: 0.7078 - val_loss: 1.0607 - val_accuracy: 0.6889


## Test the model

In [36]:
# Overall Accuracy
score = balanced_model.evaluate(test_sentences_X, y_test, batch_size=100)

55902/55902 [==============================] - 52s 929us/step


In [37]:
print("Overall Accuracy:", score[1]*100)

Overall Accuracy: 69.16747093200684


In [0]:
# Generate predictions for the test data
label_pred = balanced_model.predict(test_sentences_X, batch_size=100)

## Balanced network evaluation

Report the overall accuracy and the accuracy of  'br' and 'bf'  classes. Suggest other ways to handle imbalanced classes.

In [39]:
# Build the confusion matrix off these predictions
matrix_balanced = sklearn.metrics.confusion_matrix(y_test.argmax(axis=1), label_pred.argmax(axis=1))

# Calculate Accuracies for "br" and "bf"
sklearn.metrics.accuracy_score(y_test.argmax(axis = 1), generate_test_pred.argmax(axis = 1), normalize=True, sample_weight=None)

0.6827841579907695



### Accuracies



### Explanation


### Other ways to handle imbalanced classes


- 

- 

Can we improve things by using context information?  Next we try to build a model which predicts DA tag from the sequence of 
previous DA tags, plus the utterance representation. 

# Using Context for Dialog Act Classification

The second approach we will try is a hierarchical approach to DA tagging. We expect there is valuable sequential information among the DA tags. So in this section we apply a BiLSTM on top of the sentence CNN representation. The CNN model learns textual information in each utterance for DA classification, acting like the text classifier from Model 1 above. Then we use a bidirectional-LSTM (BLSTM) above that to learn how to use the context before and after the current utterance to improve the output.

## Define the model

This model has an architecture of:

- Word Embedding
- CNN
- Bidirectional LSTM
- Fully-Connected output



## CNN


This is a classical CNN layer used to convolve over embedings tensor and gether useful information from it. The data is represented by hierarchy of features, which can be modelled using a CNN. We transform/reshape conv output to 2d matrix. Then we pass it to the max pooling layer that applies the max pool operation on windows of different sizes.

In [0]:
filter_sizes = [3,4,5]
num_filters = 64
drop = 0.2
VOCAB_SIZE = len(wordvectors) # 43,731
MAX_LENGTH = len(max(sentences, key=len))
EMBED_SIZE = 100 # arbitary
HIDDEN_SIZE = len(unique_tags) 

from keras.layers import Conv2D,BatchNormalization,MaxPool2D,Concatenate,Reshape,Flatten, Input

# CNN model
inputs = Input(shape=(MAX_LENGTH, ), dtype='int32')
embedding = Embedding(input_dim=VOCAB_SIZE, output_dim=EMBED_SIZE, input_length=MAX_LENGTH)(inputs)
reshape = Reshape((MAX_LENGTH, EMBED_SIZE, 1))(embedding)

# 3 convolutions
conv_0 = Conv2D(num_filters, kernel_size=(filter_sizes[0], EMBED_SIZE), strides=1, padding='valid', kernel_initializer='normal', activation='relu')(reshape)
bn_0 = BatchNormalization()(conv_0)
conv_1 = Conv2D(num_filters, kernel_size=(filter_sizes[1], EMBED_SIZE), strides=1, padding='valid', kernel_initializer='normal', activation='relu')(reshape)
bn_1 = BatchNormalization()(conv_1)
conv_2 = Conv2D(num_filters, kernel_size=(filter_sizes[2], EMBED_SIZE), strides=1, padding='valid', kernel_initializer='normal', activation='relu')(reshape)
bn_2 = BatchNormalization()(conv_2)

# maxpool for 3 layers
maxpool_0 = MaxPool2D(pool_size=(MAX_LENGTH - filter_sizes[0] + 1, 1), padding='valid')(bn_0)
maxpool_1 = MaxPool2D(pool_size=(MAX_LENGTH - filter_sizes[1] + 1, 1), padding='valid')(bn_1)
maxpool_2 = MaxPool2D(pool_size=(MAX_LENGTH - filter_sizes[2] + 1, 1), padding='valid')(bn_2)

# concatenate tensors
concatenation = Concatenate( axis = -1)([maxpool_0, maxpool_1, maxpool_2])
# flatten concatenated tensors
flatten = Flatten() (concatenation)
# dense layer (dense_1)
dense_1 = Dense(HIDDEN_SIZE) (flatten)
# dropout_1
dropout_1 = Dropout(drop)(dense_1)

## BLSTM

This is used to create LSTM layers. The data we’re working with has temporal properties which we want to model as well — hence the use of a LSTM. You should create a BiLSTM.

In [0]:
# BLSTM model
timedist = TimeDistributed(Flatten()) (concatenation)
# Bidirectional 1
bidirection1 = Bidirectional(LSTM(HIDDEN_SIZE, return_sequences = True)) (timedist)
# Bidirectional 2
bidirection2 = Bidirectional(LSTM(HIDDEN_SIZE, return_sequences = False)) (bidirection1)
# Dense layer (dense_2)
dense_2 = Dense(HIDDEN_SIZE) (bidirection2)
# dropout_2
dropout_2 = Dropout(drop)(dense_2)

Concatenate 2 last layers and create the output layer

In [0]:
from  keras import Model
# concatenate 2 final layers
concatenation2 = Concatenate( axis = -1)([dropout_1, dropout_2])
# output
outputlayer = Dense(HIDDEN_SIZE, activation = 'softmax') (concatenation2)

In [43]:
# Train the model - using validation
model = Model(inputs, outputlayer)
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(train_input, train_labels, batch_size=100, epochs=3, validation_data=(val_input, val_labels))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 140000 samples, validate on 27704 samples
Epoch 1/3
140000/140000 [==============================] - 54s 389us/step - loss: 1.0821 - accuracy: 0.6759 - val_loss: 0.9082 - val_accuracy: 0.7143
Epoch 2/3
140000/140000 [==============================] - 48s 343us/step - loss: 0.7943 - accuracy: 0.7512 - val_loss: 0.9224 - val_accuracy: 0.7114
Epoch 3/3
140000/140000 [==============================] - 48s 341us/step - loss: 0.6404 - accuracy: 0.7964 - val_loss: 1.0080 - val_accuracy: 0.7058


In [44]:
score = model.evaluate(test_sentences_X, y_test, batch_size=100)

55902/55902 [==============================] - 3s 52us/step


In [45]:
print("Overall Accuracy:", score[1]*100)

Overall Accuracy: 70.46080827713013


Report your overall accuracy. Did context help disambiguate and better predict the minority classes ('br' and 'bf')? What are frequent errors? Show one positive example where adding context changed the prediction.




### Minority Classes



# Advanced:  Bert-Based Model for Dialogue Act Tagging

In the last section we want to use BERT and leverage contextual word embeddings, following on from the last lab you've 
just done. This is an advanced part of the assignment and worth 10 marks (20%) in total. You could use your BERT-based text classifier here (instead of the CNN utterance-level classifier) and see if a pre-trained BERT language model helps. The domain difference from conversational data is one possible downside to using BERT. Explore some techniques to efficiently transfer the knowledge from conversational data and to improve model performance on DA tagging.